version: "3"

services:
  web:
    # image: php:7.4-apache
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  dbdata:
