# Generated by Django 4.2 on 2023-11-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_didactica', '0002_alter_instevaluacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instevaluacion',
            options={'ordering': ['codigo'], 'verbose_name': 'Instrumento Evaluación', 'verbose_name_plural': 'Instrumentos Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='pondcriterio',
            options={'ordering': ['criterio_evaluacion__codigo'], 'verbose_name': 'Ponderación Criterios', 'verbose_name_plural': 'Ponderaciones de Criterios'},
        ),
        migrations.AlterModelOptions(
            name='pondcritud',
            options={'ordering': ['unidad__nombre', 'criterio_evaluacion__codigo'], 'verbose_name': 'Ponderación Criterios Unidad', 'verbose_name_plural': 'Ponderaciones de Criterios Unidad'},
        ),
        migrations.AlterModelOptions(
            name='pondra',
            options={'ordering': ['resultado_aprendizaje__codigo'], 'verbose_name': 'Ponderación RA', 'verbose_name_plural': 'Ponderaciones RA'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['id'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
