# Generated by Django 4.2 on 2024-01-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion_didactica', '0004_merge_20240120_2133'),
        ('core', '0005_merge_20240120_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=256, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=256, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código postal')),
                ('ciudad', models.CharField(max_length=256, verbose_name='Ciudad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriterioEvalUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_didactica.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionUDCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('crit_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_didactica.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('res_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('crit_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
            ],
        ),
    ]
