# Generated by Django 4.2 on 2024-01-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_didactica', '0003_alter_instevaluacion_options_and_more'),
        ('programacion_didactica', 'prog_didactica_migracion_inicial'),
    ]

    operations = [
    ]
