# Generated by Django 4.2 on 2023-11-24 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolioapp', '0004_remove_proyecto_categoria_proyecto_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notificado', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolioapp.proyecto')),
            ],
        ),
    ]
