# Generated by Django 4.2 on 2023-11-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_critevaluacion_options_alter_modulo_options_and_more'),
        ('programacion_didactica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instevaluacion',
            options={'verbose_name_plural': 'Instrumentos Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='pondcriterio',
            options={'verbose_name_plural': 'Ponderación Criterios'},
        ),
        migrations.AlterModelOptions(
            name='pondcritud',
            options={'verbose_name_plural': 'Ponderación Criterios Unidad'},
        ),
        migrations.AlterModelOptions(
            name='pondra',
            options={'verbose_name_plural': 'Ponderación RA'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name_plural': 'Unidad'},
        ),
        migrations.RenameField(
            model_name='instevaluacion',
            old_name='descirpcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='pondcritud',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_didactica.unidad', verbose_name='Unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='pondcritud',
            unique_together={('criterio_evaluacion', 'unidad')},
        ),
    ]
