# Generated by Django 4.2 on 2024-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptomoneda',
            name='precio',
            field=models.FloatField(),
        ),
    ]
