# Generated by Django 4.2 on 2024-01-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_critevaluacion_options_alter_modulo_options_and_more'),
        ('core', 'core_migracion_inicial'),
    ]

    operations = [
    ]
