# Generated by Django 4.2 on 2023-11-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resaprendizaje_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critevaluacion',
            options={'verbose_name_plural': 'Criterios Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='resaprendizaje',
            options={'verbose_name_plural': 'Resultados Aprendizaje'},
        ),
        migrations.RenameField(
            model_name='critevaluacion',
            old_name='descirpcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='resaprendizaje',
            old_name='descirpcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='critevaluacion',
            name='minimo',
            field=models.BooleanField(verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='critevaluacion',
            name='resultado_aprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resaprendizaje', verbose_name='Resultado de aprendizaje'),
        ),
        migrations.AlterUniqueTogether(
            name='critevaluacion',
            unique_together={('resultado_aprendizaje', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='resaprendizaje',
            unique_together={('modulo', 'codigo')},
        ),
    ]
