# Generated by Django 4.2 on 2023-11-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_critevaluacion_options_alter_modulo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critevaluacion',
            options={'ordering': ['resultado_aprendizaje__codigo', 'codigo'], 'verbose_name': 'Criterio Evaluación', 'verbose_name_plural': 'Criterios Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['codigo'], 'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='resaprendizaje',
            options={'ordering': ['codigo'], 'verbose_name': 'Resultado Aprendizaje', 'verbose_name_plural': 'Resultados Aprendizaje'},
        ),
    ]
