# Generated by Django 4.2 on 2023-12-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=33, null=True, unique=True),
        ),
    ]
