# Generated by Django 4.2 on 2023-12-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_activ',
            field=models.BooleanField(default=False),
        ),
    ]
