# Generated by Django 4.2 on 2023-12-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_myuser_is_activ_myuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
