# Generated by Django 4.2 on 2024-01-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_myuser_is_active'),
        ('usuarios', 'users_migracion_inicial'),
    ]

    operations = [
    ]
