# Generated by Django 4.2 on 2023-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_proyecto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categorias',
            field=models.ManyToManyField(related_name='proyectos', to='portfolioapp.categoria', verbose_name='Categoria'),
        ),
    ]
