# Generated by Django 4.2 on 2023-12-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_myuser_is_active_myuser_is_activ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_activ',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
