# Generated by Django 4.2 on 2023-11-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_resaprendizaje_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=256, unique=True, verbose_name='Nombre')),
                ('descirpcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=256, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PondRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resaprendizaje', verbose_name='Resultados Apredizaje')),
            ],
        ),
        migrations.CreateModel(
            name='PondCritUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('criterio_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion', verbose_name='Criterios Evaluacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_didactica.unidad', verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='PondCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje')),
                ('criterio_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion', verbose_name='Criterios Evaluacion')),
            ],
        ),
    ]
